NixOS/nixos-channel-scripts

- mirror-nixos-branch.pl
The HTML pages for each channel are showing the SHA-256 hash of each
file but the table header actually referred to it as an "SHA-512 hash".
> Fix the displayed hash name (SHA-512 -> SHA-256)

- mirror-nixos-branch.pl
The manpage says:
> The  sums  are  computed as described in FIPS-180-2.  When checking, the input should be a former
> output of this program.  The default mode is to print a line with checksum, **a space, a  character
> indicating  input  mode ('*' for binary, ' ' for text or where binary is insignificant),** and name
> for each FILE.
By adding the filename to the generated sha256 file, a user would be
able to download an iso, the sha256 file, then use `sha256 -c
[file].iso.sha256` to verify the file.
* * *
This fixes [nixos-homepage#224](https://github.com/NixOS/nixos-homepage/issues/224)
* * *
This could break assumptions where the `.sha256` files were previously used as they were. I have briefly looked and couldn't find evidence of such use.
I couldn't test the entire changes …
> Adds filename to sha256 file for use with `sha256 -c`

- file-cache.hh
```
error: [json.exception.parse_error.101] parse error at 195: syntax error - invalid string: ill-formed UTF-8 byte; last read: '"bokml'; expected string literal
```
This is most probably caused by the upgrade in [nixos-org-configurations/1b74e019b166d37a1510a99aeea86a0fa656854a](https://github.com/NixOS/nixos-org-configurations/commit/1b74e019b166d37a1510a99aeea86a0fa656854a)
that, in turn, caused nlohmann_json to go from 2.1.0 -> 3.2.0
I haven't found concrete evidence in the changelog as to a change
changing the exception type. Though, the timing for failures matches
with this update.
Furthermore, once this fix is applied, launching the update locally
works fine.
* * *
This was tested [by neutering the S3 stuff](https://gist.github.com/a4578caf7cda38a9ba8c331acfe3c45c) and running
``` …
```
> file-cache: use the right exception type for parse error

- mirror-nixos-branch.pl
From the nix 2.2 changelog:
> nix hash-file and nix hash-path now print hashes in SRI
> format by default. They also use SHA-256 by default
> instead of SHA-512 because that's what we use most of the
> time in Nixpkgs.
> mirror: sets hash format to base16

- mirror-nixos-branch.pl
PRs to NixOS are a bit confused about if they should PR to release-* or nixos-* or nixpkgs-*. I think namespacing the refs will go a long way in making it more obvious.
> Namespace channel pushes in nixpkgs

- mirror-nixos-branch.pl
Prometheus now has a configured alert if an update job fails for a
while. Going back in time is not so unusual:
1. a hydra evaluation completes with some failed jobs
2. the channel advances to this commit
3. an admin restarts a failed job
4. the channel would go backward because the evaluation is complete
Since it is not a problem, make it a non-problematic exit code.
> mirror-nixos-branch.pl: exit 0 if the channel would go back in time

- mirror-nixos-branch.pl
A more durable solution would likely be to make a generic function that
wraps backticks and fails when $? is non-zero, rather than doing it
in-situ. There are other backtick uses that may be problematic
> mirror-branch: Bails when failing to run nix-instantiate

- mirror-nixos-branch.pl
Resolving the values and being fancy is harder than the actual benefits
would give out.
Return all the info we have, and let the pager'd person deal with the
data.
>  mirror-branch: Always exit with 1 on nix-instantiate error

- mirror-nixos-branch.pl
This is intended to fix https://channels.nixos.org/nixos-19.09/store-paths.xz, which used to work at some point.
It's untested, of course.
cc @garbas @monokrome
> mirror: add redirection for store-paths.xz

- mirror-nixos-branch.pl
Hi, thank you for all your work on this package, I have a minor addendum. 
Currently, the generated github link points to the old `nixpkgs-channel` repository ([deprecated](https://github.com/NixOS/nixpkgs/issues/99257)), while still using `nixpkgs` commit hashes:
The result is that the github link 404s. 
This pull request updates the link to use `nixpkgs` proper as the repository. The correct link in this case would be [https://github.com/NixOS/nixpkgs/commits/c5147860e23ed75ce9d40298c66b416c00be1167](https://github.com/NixOS/nixpkgs/commits/c5147860e23ed75ce9d40298c66b416c00be1167).
> Update github link to use nixpkgs instead of nixpkgs-channels.

- generate-programs-index.cc
Its useful to have the `command-not-found` helper work on aarch64 systems
Probably this should be configurable somewhere (or even the databases should be separated per architecture) but this provides a quick and simple fix
> Generate indexes for aarch64 too

- mirror-nixos-branch.pl
There were some special cases for releases no longer build by Hydra.
> mirror-nixos-branch: remove special handling for old releases

- generate-programs-index.cc
It doesn't seem useful.  It takes some resources (time + RAM),
and most notably it sometimes block channel with harder-to-get logs.
> don't generate program index for i686 anymore

- mirror-nixos-branch.pl
Failure after #57 and #58 
```
Oct 27 17:09:33 bastion systemd[1]: Starting Update Channel nixos-unstable...
Oct 27 17:09:47 bastion update-nixos-unstable-start[225055]: Release information:
Oct 27 17:09:47 bastion update-nixos-unstable-start[225055]:  - release is: nixos-22.11pre421109.5bdb380ee7f (build 196583391)
Oct 27 17:09:47 bastion update-nixos-unstable-start[225055]:  - eval is: 1784092
Oct 27 17:09:47 bastion update-nixos-unstable-start[225055]:  - prefix is: nixos/unstable/nixos-22.11pre421109.5bdb380ee7f
Oct 27 17:09:47 bastion update-nixos-unstable-start[225055]:  - Git commit is: 5bdb380ee7fa036d47b19e9d854928f4881c50a1
Oct 27 17:09:48 bastion update-nixos-unstable-start[225055]: previous release is https://releases.nixos.org/nixos/unstable/nixos-22.11pre420742.f994293d1eb …
```
> Fix typo in system name for ova image

- mirror-nixos-branch.pl
We are lacking redirects for the release :cry:
> mirror-nixos-branch: Create redirects for aarch64-linux ISOs

- mirror-nixos-branch.pl
Tested that the script runs with appropriate credentials on `bastion` right now, but I haven't end-to-end tested this change. My testing was running the `nix store cat` command as `hydra-mirror` on bastion.
----
The channel scripts hit into NixOS/nixos-org-configurations#212 sometimes when fetching ISOs from cache.nixos.org to copy to the channels bucket. This makes runs take hours when they should take minutes.
There is no benefit gained from going through cache.nixos.org for this use case. As noticed by @K900, the .iso nar.xz files on the cache are unlikely to be touched by anyone other than the channel scripts, so we don't even end up pre-warming the cache or anything along those lines - if anything, we just waste cache bytes that could be used by other paths.
Fixes #67.
> mirror-nixos-branch: fetch channel artifacts from S3 directly

- flake.nix
> Parallelize xz by default

- mirror-nixos-branch.pl
See https://github.com/NixOS/nixpkgs/pull/338433.
I’m not very good at Perl and I don’t know how to test these scripts, so I’d appreciate some scrutiny here.
> mirror-nixos-branch: omit minimal ISOs from small channels

- mirror-nixos-branch.pl
This is part of another PR over in NixOS/infra (https://github.com/NixOS/infra/pull/562) that implements the configuration change needed for Fastly and allows one to use
~~~nix
{
inputs = {
nixpkgs.url = "https://channels.nixos.org/nixos-unstable-small/nixexprs.tar.xz";
};
}
~~~
and have it locked in flake.lock accordingly.
This has multiple advantages over using something like github:NixOS/nixpkgs/nixos-unstable-small.
For example, channels.nixos.org and releases.nixos.org are accessible on not just IPv4 but also IPv6, unlike GitHub.
Furthermore, the tarballs have a higher compression-ratio than those served by GitHub and thus require less bandwidth to download.
Additionally, nixexprs.tar.xz contains the precomputed programs.sqlite which enables the use of the very lightweight …
> mirror-nixos-branch: add header for "Lockable HTTP Tarball Protocol" (Flakes)

- mirror-nixos-branch.pl
We will prune the query string in fastly instead.
> simplify the tarball lock protocol
